name: Shell Commands

on:
  push:
    branches:
      - main  # Adjust this to your desired branch

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo String
        run: echo "Hello google@Andre what is your focus for today."
      - name: Multiple String
        run: |
          node -v
          npm -v