name: Shell commands

on:
  push:
    branches:
      - main  # Adjust this to your desired branch

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Echo string
        run: echo "Hello google@Andre what is your focus for today."

      - name: Multiple strings
        run: |
          node -v
          npm -v  # Corrected from mpm -v

      - name: Python command
        run: |
          python -c "import platform; print(platform.processor())"

  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash
